title: Finlay Dunn # your name (or website title) here
logo: "/headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an MSBA student at the University of Utah, David Eccles School of Business. I am currently working at Layton Construction as a Data Analyst Intern.  
  <br><br>
  Check out the README for information on my projects in this portfolio 
  <br><br>
  <a href="https://www.linkedin.com/in/finlay-dunn-a86024237/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
